### ISSUE TITLE
How to purge old data

### ISSUE THREAD

**Issue by benbrummer** [nextcloud/user_external#112]
After removing user_external database still shows the table created for this app. Is there a way to purge this tables optionally when uninstalling the app?

**Comment by violoncelloCH** [comment]
This is by design. Uninstalling a Nextcloud app doesn't remove it's data in case you want to reinstall it later. Also this would be really dangerous in case of user_external because you'd also remove user accounts. (Or at least part of the accounts; the data folder and other references will still remain.)
If you're really sure what you're doing you can of course delete the tables manually.
