### ISSUE TITLE
Change from IMAP login to regular login

### ISSUE THREAD

**Issue by ariselseng** [nextcloud/user_external#19]
Hello,
What can I do to either rename username and make an IMAP user a regular user, or disable IMAP for a certain user and set a password inside nextcloud?

**Comment by jnagler** [comment]
I have the same question as @pierreozoux but changing to SMB instead of IMAP. I also posted a support request in the Nextcloud help forum [https://help.nextcloud.com/t/change-user-backend-for-existing-user/56207](url) which included same insights I realized:

Regular logins' credentials are stored in table oc_users with (uid, displayname, password) while SMB users are stored in table oc_users_external with (backend, uid, displayname). Both uids are the username and it seems all other tables, e.g. oc_accounts or oc_group_users simply refer to a uid in one of those two tables without knowing which one has defined the login credentials (direct password comparison or backend password confirmation).

I assume it may be that simple to switch to maintenance mode and to manually add an uid to oc_users_external and then delete this equivalent uid from oc_users. This may seamlessly change the backend for this uid. Or do I oversee something?

I thought this could easily be answered with a yes or no but if not I could offer to check the code how oc_users_external interferes at all in core processes of Nextcloud or at least could do a test whether it works - but of course a test only may not reveal deeper problems corrupting the whole Nextcloud instance later on...

**Comment by violoncelloCH** [comment]
> I assume it may be that simple to switch to maintenance mode and to manually add an uid to oc_users_external and then delete this equivalent uid from oc_users. This may seamlessly change the backend for this uid. Or do I oversee something?

@jnagler thanks for investigation... from what I know, that could indeed be working, however I would recommend to test this extensively before doing it in production...
I assume it may be that simple to switch to maintenance mode and to manually add an uid to oc_users_external and then delete this equivalent uid from oc_users. This may seamlessly change the backend for this uid. Or do I oversee something?
If you have the time to dive deeper and check the code for it, go on :) I'm not yet that familiar with the Nextcloud core (sadly), so I would appreciate it, if you could check this...

**Comment by Mannshoch** [comment]
I would like to see if this may end in a tool to move User between authenticator.

In my opinion the existence of an user should have nothing to do with the check for validity. #2

**Comment by violoncelloCH** [comment]
of course, that would be best... so maybe a script or a separate app which could handle that.

In general user_external has it's own table to save successfully authenticated users toghether with the respective authentication backend. So it should be possible to compare a regular user with a user from user_external to see what needs to be changed. In the end what's relevant is the uid (user-name) or for ldap it's a random uuid. Note that there is also a datadirectory with the name of the uid which needs to correspond.

**Comment by jnagler** [comment]
I now found time to do more tests.

1. With an external backend configured any uid not yet existing as a local NC user but being found in the backend with matching password can log into NC and this will create an entry in oc_users_external. Changing the password in the NC Settings is disabled (this only relies on an oc_users entry).
2. Creating a user with the same uid existing in the backend in NC before this uid attempted to log in (see 1.) creates an entry in oc_users only.
3. If the passwords in NC and the backend are identical and the user logs in then no oc_users_external is created. But whenever the password in NC and the backend differ using the one from the backend the first time this uid is also created in oc_users_external.

This means having a backend configured NC seems to always check given uid and password against the local oc_users entry as well as the backend. If one matches you are successfully authenticated and the external match is noted in oc_users_external.

With having both entries removing the one in oc_users manually from the table but leaving the oc_users_external seems to exactly lead to the initial behaviour of 1.

I also checked deleting an user in NC with both oc_users and oc_users_external entries and it seems to behave as follows: In the first instance it deletes the oc_users entry together with all his data and the user will disappear from the users list. But reloading it the user reappears (based on his oc_users_external entry). Deleting it again completely removes the user. It seems the only relict was the oc_users_external entry which is finally purged with the 2nd deletion.

**Comment by Mannshoch** [comment]
What's about the new User Migration tool in Nextcloud 24? Does this feature gives a new oportunity for this case?

**Comment by sebix** [comment]
See also https://github.com/nextcloud/user_external/issues/187

**Comment by pierreozoux** [comment]
I think we can close this issue.

This is a kind of advanced use case, I don't think it will be solved by the app itself, it will always be some custom solution.

If people want to PR doc, feel free.

If you need help, ask on the forum.

In the meantime, I'm closing.
