### ISSUE TITLE
Support NC v25

### ISSUE THREAD

**Issue by VVD** [nextcloud/user_external#210]
Yesterday is out NC v25.

**Comment by brad2014** [comment]
A note: If an installation is upgraded to NC v25, users who are authenticated via user_external (e.g. IMAP) will be locked out, because the user_external app, required for logging in, will be silently and automatically disabled.

Workaround: The app can be reenabled manually using nextcloud/occ (run as the nextcloud owner, e.g. apache)

% occ  app:enable user_external --force

**Comment by Glandos** [comment]
I forced the activation of the app, and it works with NC25 + IMAP

**Comment by p-bo** [comment]
Just in case it wasn't noticed - Nextcloud improved policy regarding changes in core to ease app developers in maintaining compatibility with newer Nextcloud versions:

https://help.nextcloud.com/t/new-process-for-documenting-core-code-changes-that-affect-app-developers/149828?u=p-bo

**Comment by p-bo** [comment]
> does this app need any extra maintainers
Most probably any maintainer(s) at all:
https://github.com/nextcloud/user_external/graphs/contributors

**Comment by violoncelloCH** [comment]
hey thanks for reporting ! I'm maintaining this app in my sparse spare time...

I've just released a new version v3.1.0 which is compatible with NC25
#212

**Comment by VVD** [comment]
Released, but without fix for PHP 8.1: https://github.com/nextcloud/user_external/issues/203 :-(
