### ISSUE TITLE
Add to app store

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/user_external#22]
@violoncelloCH @MorrisJobke @rullzer @nextcloud/user_external we should probably put the app in the app store, right?

@violoncelloCH do you want to do that? :)

**Comment by violoncelloCH** [comment]
Yes, I will try to do this. (Will maybe need some guidance.)
I'm actually reading the documentation on how to publish an app to the appstore :)

**Comment by jancborchardt** [comment]
@violoncelloCH note down any issue that you encounter, however small it may be! We can use that to improve the flow and documentation for everyone coming after you. :heart:

**Comment by violoncelloCH** [comment]
@jancborchardt 
I primarily struggled with the permissions, because the `occ integrity:sign-app` command needs to be run as `www-data`, but `www-data` doesn't have access to the private key, which is saved in my primary user's home directory on my laptop.

The other thing I didn't expect is that `occ integrity:sign-app` also adds the files in the hidden `.git/` directory into `signatures.json` and there is (AFAIK) no option to exclude this directory. So the only way is to copy the whole folder of the app to another location and then remove `.git/` as well?? 
(For `tar` i can simply do `--exclude .git/`)

I now added the first release to the appstore and hope it worked. I guess it simply takes some time or need some manual steps on your side? There was no real feedback except a spinning circle on the "Upload" button. The form stayed with the content filled in after the spinning circle disappeared again. Maybe that could be improved in terms of UI design. Also an information text for the first time uploader about when he can expect the app/release to be visible in the appstore would be nice.
 
If I'm right, I can't set an individual publisher for each app, so the only way to set it to Nextcloud would be to set my whole appstore account to the name "Nextcloud". Should I do this?

**Comment by jancborchardt** [comment]
Cool! :) Best open these problems as separate issues. The first 2 ones I think go into the [server](https://github.com/nextcloud/server/) repository cause that’s where the occ command lives. And the 3rd one goes to the [appstore](https://github.com/nextcloud/appstore/).

> If I'm right, I can't set an individual publisher for each app, so the only way to set it to Nextcloud would be to set my whole appstore account to the name "Nextcloud". Should I do this?

As @MorrisJobke said in https://github.com/nextcloud/user_external/pull/26#issuecomment-451590387: "Not needed. Just leave it as it is now." – also it would be very confusing if another account would be named "Nextcloud". ;)

**Comment by jancborchardt** [comment]
Also so far, it said only @icewind1991’s name in there, so it would be good to add him as a collaborator on the appstore interface. :)
![](https://user-images.githubusercontent.com/15013924/50424529-74dde700-08a0-11e9-8bf6-4e0614004d85.png)

**Comment by MorrisJobke** [comment]
> Also so far, it said only @icewind1991’s name in there, so it would be good to add him as a collaborator on the appstore interface. :)

That is from the info.xml.

And the error you get is not from the appstore, because the app is not uploaded there yet: https://apps.nextcloud.com/apps/user_external

**Comment by MorrisJobke** [comment]
See https://github.com/nextcloud/user_external/pull/26#issuecomment-451879861 for the steps.

**Comment by violoncelloCH** [comment]
The app is finally released! See https://apps.nextcloud.com/apps/user_external

@jancborchardt 
isn't the first point more something for the documentation(s)? `occ` needs to be run with the webserver user, so it all depends on the filesystem permissions which need to be changed manually.  
for the second one I'll create an issue; for the third point @MorrisJobke already created nextcloud/appstore#590

**Comment by violoncelloCH** [comment]
for point two: nextcloud/server#13408
