### ISSUE TITLE
Nextcloud 28 support

### ISSUE THREAD

**Issue by VVD** [nextcloud/user_external#240]
IMAP authentication method work for me after edit appinfo/info.xml(36):
```
-                <nextcloud min-version="25" max-version="27" />
+                <nextcloud min-version="25" max-version="28" />
```

**Comment by Nordlead75** [comment]
Hello
When did you think that a new relaese ?

**Comment by madalinignisca** [comment]
Hi. When can we expect a release?

**Comment by pm-pm** [comment]
Last App for upgrade to NC 28 is possible. Please continue. ;-)

**Comment by joe-average-user** [comment]
If it works by simply increasing the max-version I am all for it.
Great App!

**Comment by prismopensource** [comment]
Looks like Nextcloud doesn't show much love for this project anymore. Is there any way to help or sponsor this project?

**Comment by joe-average-user** [comment]
Hm, I dont know much about the project, but I guess we should rather ask the maintainer to release a nc28 compatible version. Nextcloud itself should not have a lot to do with that. Since the app is signed someone's got to be the maintainer ...
He needs to sign it and release it, he has got the keys.

**Comment by joe-average-user** [comment]
Don't get me wrong, I am all for this app. I find it quite useful. Still the situation is that there is a pending patch #241 that only needs a review to be released. This does not sound like a ultimately critical situation where someone "from above" needs to jump in and save the world. Hopefully one of the guys with write access comes along and does the review click ...

**Comment by Aaron-Ritter** [comment]
Hi @come-nc @skjnldsv @violoncelloCH,

As you are some of the latest committer for nextcloud/user_external I was hoping you could help us to find out what we could do to get the Compatibility with nextcloud 28 commited. As the issue is now open since soon 3 months.

Is there anything which can be done with regards to testing by side what has already been done? Really hope for your input and direction.

Thanks,
Aaron

**Comment by VVD** [comment]
Thanks!
And create release please too.

**Comment by El-Gavy** [comment]
> Don't get me wrong, I am all for this app. I find it quite useful. Still the situation is that there is a pending patch #241 that only needs a review to be released. This does not sound like a ultimately critical situation where someone "from above" needs to jump in and save the world. Hopefully one of the guys with write access comes along and does the review click ...

Patch has been merged so problem solved?

**Comment by prismopensource** [comment]
Not without a release it isn't for most.

**Comment by El-Gavy** [comment]
> Not without a release it isn't for most.

Ah, release is needed to be able to update in Nextcloud administration? (sorry, didn’t know)

**Comment by prismopensource** [comment]
I'm afraid so, at the point it would be nice to add support for version 29 directly as well.

**Comment by VVD** [comment]
29 is soon.

**Comment by alucardx01** [comment]
What does it take for someone to do a release? The fix was very easy and this is in the official Nextcloud documentation. If it is not going to get upgraded along with Nextcloud it really shouldn't be in the docs.

**Comment by prismopensource** [comment]
> 29 is soon.

Opened up a [new feature request](https://github.com/nextcloud/user_external/issues/246) for that.
