### ISSUE TITLE
Basic auth fails with 3xx redirection

### ISSUE THREAD

**Issue by windware** [nextcloud/user_external#45]
### Steps to reproduce
1. Use "OC_User_BasicAuth" class.
2. Login with a URL with basic auth that redirects upon successful login attempt.

### Expected behaviour
Login should also succeed with 3xx redirect status codes.

### Actual behaviour
Only succeeds by receiving 2xx status codes.

### Affected Authentication backend
OC_User_BasicAuth

### Server configuration

**Operating system**:
Ubuntu 18.04

**Web server:**
Nginx

**Database:**
MySQL

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
From official zip.

**Comment by nerdmaennchen** [comment]
I see that the current behavior is not the desired behavior. 
AFAIK it absolutely makes sense to follow redirects if need be.

But what would a reasonable behavior be (I honestly dont know)?
A redirect response could be treated as a positive authentication but depending on the HTTP server sertup might actually be a redirect to a page where the "actual" authentication happens.

So from my rather little knowledge about HTTP there are two ways to fix the behavior:
- Either follow the redirects until the server responds with a 2xx response
- Treat the 3xx response as an acknowledgement

Or am I missing something?

all the best and thanks for raising this!
Lutz

**Comment by windware** [comment]
It would work accurately if you follow all of 3xx redirects while sending the basic auth header until you hit non 3xx status, and do the same detection as now to check if it landed on 2xx.

Also it is safe to have max redirects set to [20](https://stackoverflow.com/questions/9384474/in-chrome-how-many-redirects-are-too-many) to avoid infinite loop, in which case, it should fail as 'too many redirects'.

**Comment by violoncelloCH** [comment]
thank you for the report @windware 
and thank you for taking care @nerdmaennchen 

I would not treat the 3xx response as an acknowledgement, because this could lead to security issues. (e.g an unaware admin could configure it against a server which redirects, what would lead to all login attempts being accepted)
On the other hand, as said, following too many redirects would lead to performance issues, so there should definitely be a max redirect number. 
So I would go for following a small number of redirects (maybe even only 5-10) until we get a 2xx response. But we should also indicate in the documentation, that the basic auth server should work/be configured with the smallest number of redirects possible.

@nerdmaennchen would you be up for implementing this? :)

**Comment by windware** [comment]
> maybe even only 5-10

In the post I linked for '20', it says most browsers (except old IE) allows at most 20 redirects until it throws an error, so I'd assume it's safe to allow as much redirects to avoid any further complaints and for anyone having performance problem, it's their problem of having have to redirect a dozen time and not the implementation's.

**Comment by nerdmaennchen** [comment]
I'm more than happy to integrate the suggestions.
But please don't wory if it takes more than a week.
I'm currently in Belize and very easily distracted by the djungle, sea and people.
Oh and the internet connection is terribly slow... Haha

All the best,
Lutz

**Comment by violoncelloCH** [comment]
cool!
no problem, just take your time :) a high quality contribution is better than a fast one ;)
(I've added it to the 0.5.2 milestone, but we can simply move it to the next one if it's not ready for the release)
enjoy your holidays
