### ISSUE TITLE
IMAP: make striping the @domain.part optional (if mail domain is specified)

### ISSUE THREAD

**Issue by Thom1b** [nextcloud/user_external#68]
### Steps to reproduce
1. Add a specified domain in config.php for IMAP authentification
2. Login with an existing IMAP user (user@example.org)

### Expected behaviour
"user@example.org" is logged on his nextcloud account.

### Actual behaviour
a new user simply called "user" is created because (I quote): "After successfull login the domain part will be striped and the rest used as username in Nextcloud. e.g. 'username@example.com' will be 'username' in Nextcloud."

### Affected Authentication backend
IMAP

### Server configuration

**User External App version:**
0.6.1

**Operating system:**
Slackware GNU/Linux (4.4.178)

**Web server:**
nginx-1.14.2

**Database:**
mariadb-10.3.14

**PHP version:**
7.3.4

**Nextcloud version:**
15.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Where did you install Nextcloud from:**
I use official tarball from nextcloud.com

Maybe I misunderstood how should work IMAP with specified domain. When I used the old user_external app (until 0.5), it wasn't possible to specifiy a domain. It could be nice to specify one without stripping the domain part and still use "'user@example.org" as username.

Have a nice day!

PS: last important thing: I was afraid to see "user_external" dying so I'm glad to see people works on it. Thanks a lot! :)

**Comment by violoncelloCH** [comment]
thank you for the report!
unfortunately this is intended functionality and part of user_external since two years or so (long before I started to maintain it): when specifying the imap domain, the @domain.part is striped away from the user name... 
so if you don't want it to be striped away, don't specify the domain (as you already wrote)... as this is now a feature since quite a while it doesn't make sense to simply revert it just like that... What could be done is an additional option to make this option (however we should keep the default as it is now)...
As a busy student maintaining this in my free time, I don't have the time to do this (at least for the near future)... however PRs are always welcome! If you need help implementing it I'm also happy to help :)

**Comment by Thom1b** [comment]
Hi, thanks for your answer.

I didn't know it was already running this way with the old user_external. My goal was to restrict access to users "*@example.org", so users like "*@example.net" can't use nc. Anyway I can live without this restriction, don't worry about that. :)

I don't code so it's hard for me to help. I think you can close this issue.

I thank you again for your job. Have a nice day! :)

**Comment by violoncelloCH** [comment]
let's keep it open as a feature request :)
