### ISSUE TITLE
Rename new imap backend OC_IMAP_Auth2

### ISSUE THREAD

**Issue by mmccarn** [nextcloud/user_external#72]
I'd like to propose that User_External use a different 'user_backend' for the new vs old imap -- especially since the back-ends are so different, with differing data and configuration requirements.

Option 1 [protect admins still using v0.5.0 during upgrades]:
- rename the new version as OC_User_IMAP2
  - users whose app gets updated automatically with NextCloud are not required to edit config.php to get imap authentication reconfigured
  - users depending on the old version do not need to worry about breakage during app upgades
  - users who want to use the new version have to change the 'user_backend' string at the same time that they have to change all of the configuration options

Option 2 [protect admins already using v0.6.x during upgrades]:
- add back the legacy imap support as backend 'OC_User_IMAP_Legacy'
  - users who have v0.6.x working do not need to edit config.php to get imap authentication reconfigured
  - users whose app gets upgraded automatically with NextCloud can change the user_backend from `OC_User_IMAP` to `OC_User_IMAP_Legacy` instead of changing all of the other settings related to IMAP.

Option 3 [disconnect user_external from IMAP Authentication to protect admins during upgrades]:
- fork user_external v0.5.0, rename it, and rename the user_backends to avoid naming conflicts:
[imap_auth](https://github.com/mmccarn/nextcloud-imap_auth/tree/imap_auth)

**Comment by violoncelloCH** [comment]
I can understand the idea behind that and it would certainly have been a nice idea to leave the admins time to migrate like that... however I think it's to late for that now; it doesn't make sense to revert everything again now... only option that could make sense would be option 2; however this would need database migrations as well to not loose existing shares and stuff (see #64)...
unless there is a big demand for it, I don't think it makes sense to re-add the old imap as a legacy option... not last because of security concerns if users keep the legacy method "forever"...

So, sorry, but I tend to close this...
